FROM node:alpine as builder
LABEL description='Spystore React'
WORKDIR '/app'
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

ENV REACT_APP_SPYSTORE_API_URL=http://localhost:32768
ENV REACT_APP_SPYSTORE_USERID=1

FROM nginx
EXPOSE 80
COPY --from=builder /app/build /usr/share/nginx/html
# COPY --from=builder /app/nginx.conf /etc/nginx/conf.d/default.conf
